### ISSUE TITLE
Upgrade cmake crate version to support Visual Studio 2022

### ISSUE THREAD

**Issue by Bktero** [eclipse/paho.mqtt.rust#170] opened 2022-10-07 14:45 UTC
Hi!

I am trying to use Paho MQTT but I have Visual Studio 2022 installed on my computer.

[`Cargo.toml` from `paho-mqtt-sys`](https://github.com/eclipse/paho.mqtt.rust/blob/master/paho-mqtt-sys/Cargo.toml) has `cmake = { version = "=0.1.45", optional = true }` as dependency.

Support for Visual Studio 2022 was added in [CMake 3.21](https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2017%202022.html) and in [by this commit in cmake-rs 0.1.48](https://github.com/rust-lang/cmake-rs/commit/dca4a9df71df40eeb57b974703d745607b168d9f).

As a consequence, when I try to `cargo build` my project, I get an error:

```
  thread 'main' panicked at 'Visual studio version detected but this crate doesn't know how to generate cmake files for it, can the `cmake` crate be updated?', C:\Users\z19100018\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.45\src\lib.rs:792:22
```

Can you upgrade the version of `cmake-rs` in the dependencies and release a new version of Paho MQTT please?

Best regards :)
Bktero

**Comment by thepperson** [comment] 2022-10-19 13:08
I am also running into this problem.

**Comment by fpagliughi** [comment] 2022-10-23 16:22
Yeah, for context, we needed to pin the cmake crate at 0.1.45, due to an issue with the following version (0.1.46) which made it unusable with any cmake < v3.12.

See #137

It seems that the issue may be fixed with the v0.1.48 crate, but I don't even have an older version of CMake to test against on any of my development machines anymore!  So I will hope for the best and update the dependency.

**Comment by fpagliughi** [comment] 2022-10-23 18:19
BTW, this is a duplicate of #147

**Closed by fpagliughi** 2022-10-23 18:19 UTC
Labels: duplicate, fix added

**Comment by Bktero** [comment] 2022-10-24 07:18
Sorry for the duplicate. 

Thanks for the fix :)

I read some comments in the code about instability with a higher version of CMake create. Indeed, dropping support for old versions can be a pain for people. However, CMake 3.12.0 was [released in July 2018](https://www.kitware.com/cmake-3-12-0-available-for-download/), so it may seem reasonable to drop support for older versions.
